### PR TITLE
Revisit this Branch to fix a PHP error

### PR DESCRIPTION
**Pull request by jhogue**
I think this error comes up because the variable is not defined outside of the if statements. I turned two `if` statements into one `if/else`. Addresses Issue #13

### CODE REVIEW

**Comment by jhogue** [comment]
I can't test since I do not have a working local but please let me know if this addresses the warnings you are seeing with wp-debug on.

**Comment by kangabell** [comment]
just noting that this fixes https://github.com/highchair/pps/issues/13

**Comment by kangabell** [comment]
@jhogue this is better, but I'm still getting one error:
```Notice: Object of class WP could not be converted to int in /Users/kbell/Code/pps/wp-content/themes/pps-2017/functions.php on line 150```

**Comment by jhogue** [comment]
I don't get it. The `get_current_blog_id()` function returns an integer. So, maybe this is one of those things where you need to store the result in a variable and not call it inside of an `if` declaration. Please try my update and let me know if it still throws a message please.

**Comment by jhogue** [comment]
Got it working without PHP errors or notices. This code is already live on the site, verified that the Guide site gets the `-5` GA id instead of the default `-1`.

**Comment by kangabell** [comment]
Did you look into enqueuing this instead? Makes me a little uncomfortable that it's not enqueued.

**Pull request merged**
